from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 360)
        MainWindow.setMinimumSize(QtCore.QSize(300, 200))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileselect = QtWidgets.QGroupBox(self.centralwidget)
        self.fileselect.setObjectName("fileselect")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.fileselect)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.file_text = QtWidgets.QLineEdit(self.fileselect)
        self.file_text.setObjectName("file_text")
        self.horizontalLayout_7.addWidget(self.file_text)
        self.file_button = QtWidgets.QPushButton(self.fileselect)
        self.file_button.setObjectName("file_button")
        self.horizontalLayout_7.addWidget(self.file_button)
        self.verticalLayout.addWidget(self.fileselect)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.discard_button = QtWidgets.QCheckBox(self.centralwidget)
        self.discard_button.setObjectName("discard_button")
        self.gridLayout.addWidget(self.discard_button, 2, 4, 1, 1)
        self.limit_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.limit_spinbox.setMinimumSize(QtCore.QSize(60, 0))
        self.limit_spinbox.setObjectName("limit_spinbox")
        self.gridLayout.addWidget(self.limit_spinbox, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.dpi_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.dpi_spinbox.setMinimumSize(QtCore.QSize(60, 0))
        self.dpi_spinbox.setObjectName("dpi_spinbox")
        self.gridLayout.addWidget(self.dpi_spinbox, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.progress_text = QtWidgets.QLabel(self.centralwidget)
        self.progress_text.setObjectName("progress_text")
        self.horizontalLayout_6.addWidget(self.progress_text)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_6.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Seperate Print"))
        self.fileselect.setTitle(_translate("MainWindow", "PDF File"))
        self.file_button.setText(_translate("MainWindow", "Select"))
        self.label_6.setText(_translate("MainWindow", "Rendered DPI"))
        self.discard_button.setText(_translate("MainWindow", "Discard Empty Pages"))
        self.label_7.setText(_translate("MainWindow", "Color Limit"))
        self.progress_text.setText(_translate("MainWindow", "Waiting for input..."))
        self.start_button.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
